name: 'Remove Repository Collaborator'
description: 'Removes a collaborator from a repository'

inputs:
  repository:
    description: 'Target repository in the format "owner/repo"'
    required: true
  collaborator:
    description: 'GitHub username of the collaborator to remove'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Remove collaborator
      shell: bash
      env:
        REPO: ${{ inputs.repository }}
        COLLABORATOR: ${{ inputs.collaborator }}
      run: |
        echo "================================================"
        echo "🗑️  REMOVE COLLABORATOR"
        echo "================================================"
        echo "📂 Repository: $REPO"
        echo "👤 Collaborator: $COLLABORATOR"
        echo "🔗 API Endpoint: https://api.github.com/repos/$REPO/collaborators/$COLLABORATOR"
        echo "================================================"
        echo ""
        
        echo "🚀 Sending DELETE request..."
        RESPONSE=$(curl -s -w "\n%{http_code}" -X DELETE \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/$REPO/collaborators/$COLLABORATOR")
        
        HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
        BODY=$(echo "$RESPONSE" | head -n -1)
        
        echo "📡 HTTP Status Code: $HTTP_CODE"
        echo ""
        
        if [[ "$HTTP_CODE" == "204" ]]; then
          echo "✅ Collaborator removed successfully"
          echo ""
          echo "ℹ️  User '$COLLABORATOR' no longer has access to '$REPO'"
        elif [[ "$HTTP_CODE" == "404" ]]; then
          echo "⚠️  Not Found (HTTP 404)"
          echo ""
          echo "🔍 Possible causes:"
          echo "   - Collaborator '$COLLABORATOR' was not found in repository"
          echo "   - Collaborator was already removed"
          echo "   - Repository '$REPO' doesn't exist"
          echo "   - User '$COLLABORATOR' doesn't exist"
          echo ""
          echo "ℹ️  No action needed if user is already removed"
        elif [[ "$HTTP_CODE" == "403" ]]; then
          echo "❌ Forbidden (HTTP 403)"
          echo ""
          echo "🔍 Possible causes:"
          echo "   - Token doesn't have admin permissions on the repository"
          echo "   - Cannot remove repository owner"
          echo "   - Organization policies prevent removal"
          echo ""
          echo "📄 Response body:"
          echo "$BODY" | jq '.' 2>/dev/null || echo "$BODY"
          exit 1
        else
          echo "❌ Failed to remove collaborator (HTTP $HTTP_CODE)"
          echo ""
          echo "📄 Response body:"
          echo "$BODY" | jq '.' 2>/dev/null || echo "$BODY"
          exit 1
        fi
